### ISSUE TITLE
DISABLE_DD_AGENT prevents the app from booting up at all

### ISSUE THREAD

**Issue by Ferdy89** [DataDog/heroku-buildpack-datadog#11]
It looks like the intended behavior for the flag is to just skip the step where the agent is started, but instead it exits the initialization of the app completely. Per Heroku's docs about the buildpack API, [files in `.profile.d/` are sourced](https://devcenter.heroku.com/articles/buildpack-api#profile-d-scripts), which means that calling `exit` (whether it exits with `0` or `1`) will exit the caller as well.

We ran into this issue ourselves and [the fix we made](https://github.com/avantcredit/heroku-buildpack-datadog/pull/1/commits/d84e2e9d9fc0fc1c4bbb480808d1f032943c153b) was to basically wrap the whole script in an `if ... fi` instead of using `exit`. I would be happy to make a PR for this if you wanted me to.

**Comment by dblackdblack** [comment]
+1

**Comment by jyee** [comment]
Thanks! I've been working in the jyee/merge_upstream branch to eventually get this merged back into mike's original repo and I've got this change made there.

**Comment by jyee** [comment]
Sorry, the effort to merge back upstream to the original project has stalled a bit, so I've merged that branch back into the master for this repo.

**Comment by Ferdy89** [comment]
Thanks @jyee! I'm looking at that branch you mentioned and the problem I'm still seeing is that is uses [`exit` very liberally](https://github.com/DataDog/heroku-buildpack-datadog/commit/f1f4e21797b8718d27c4f03a01dcb69259c99c49#diff-84f61b044cd8a7b62df178b83f0ad2a9R11). `exit` silently kills the app completely, which is pretty aggressive considering DataDog is more of an addon than the core app. I don't think missing config vars for DataDog should bring down the application completely.

**Comment by jyee** [comment]
@Ferdy89 I just removed the other `exit` commands in the latest commit.
