### ISSUE TITLE
Heroku doesn't start on Heroku stack-18 buildpack

### ISSUE THREAD

**Issue by tehkaiyu** [DataDog/heroku-buildpack-datadog#112]
Just upgraded my stack from cedar-14 to 18. Build works fine after I cleared the cache with `heroku repo:purge_cache`. 

But when the app runs I see this error `/app/.apt/opt/datadog-agent/bin/agent/agent: error while loading shared libraries: libdatadog-agent-six.so.1: cannot open shared object file: No such file or directory`

Neither `host` nor `metrics` show up in DataDog

**Comment by coop** [comment]
I am having the same problem. For me I am on the same stack but dd upgraded from 6.11.3-1 to 6.12.0-1. I am about to pin to 6.11.3-1. I will update my comment shortly.

Env: Heroku

**Comment by calston** [comment]
> I am having the same problem. For me I am on the same stack but dd upgraded from 6.11.3-1 to 6.12.0-1. I am about to pin to 6.11.3-1. I will update my comment shortly.
> 
> EDIT: after pinning to 6.11.3-1 statsd is back.

Would you mind saying how? There are no proper tags, branches, or releases on this repo :(

**Comment by naliwajek** [comment]
Found it. @calston - `DD_AGENT_VERSION` env var :+1:

**Comment by gauravmk** [comment]
We had the same issue this morning. pinning `DD_AGENT_VERSION` fixed it for us

**Comment by rgdutta** [comment]
> Found it. @calston - `DD_AGENT_VERSION` env var 👍
> 
> **Edit**: I can confirm setting `DD_AGENT_VERSION` to `6.11.3-1` mentioned by @coop works.

Just make sure for heroku its  6.11.3-1_amd

**Comment by burningion** [comment]
Hey all,

Apologies for this! Indeed, the release of the Agent 6.12 broke the buildpack. 

This should now be fixed in the latest buildpack.

The Datadog Agent team is in the process of moving away from Python 2.7, as it's EOL by the end of the year.

One of the new dependencies introduced in the transition period was missed in this script (`libdatadog-agent-six.so.1`). It should now be included with the latest release of the buildpack. 

We're working on a way to pin the Agent version that makes sense out of the box, preventing these sort of unexpected version changes in the future. 

Apologies for the any headaches this may have caused, and thanks for helping both diagnosing and providing solutions here on Github.

**Comment by teoljungberg** [comment]
We're running `6.12.1-1` and we are still receiving the warnings. Is there anything more we can do to resolve the issue?

**Comment by jyee** [comment]
@teoljungberg Have you rebuilt your slugs using the latest buildpack? The fix is in the buildpack, not the Datadog Agent.
