### ISSUE TITLE
Logs dumped to stdout/stderr during `heroku run rails c`

### ISSUE THREAD

**Issue by justincampbell** [DataDog/heroku-buildpack-datadog#23]
When running a Rails console, I see the following log lines:

```
2018-01-09 14:39:27 UTC | INFO | (runner.go:298 in work) | Done running check load                                                                                              [45/1351]
2018-01-09 14:39:27 UTC | INFO | (runner.go:242 in work) | Running check memory
2018-01-09 14:39:27 UTC | INFO | (runner.go:298 in work) | Done running check io
2018-01-09 14:39:27 UTC | INFO | (runner.go:242 in work) | Running check ntp
2018-01-09 14:39:27 UTC | INFO | (runner.go:298 in work) | Done running check memory
2018-01-09 14:39:27 UTC | INFO | (runner.go:242 in work) | Running check uptime
2018-01-09 14:39:27 UTC | INFO | (runner.go:298 in work) | Done running check uptime
2018-01-09 14:39:32 UTC | INFO | (ntp.go:135 in Run) | There was an error querying the ntp host: read udp 172.16.52.210:34176->64.113.44.55:123: i/o timeout
2018-01-09 14:39:32 UTC | INFO | (runner.go:298 in work) | Done running check ntp
2018-01-09 14:39:32 UTC | INFO | (apm.go:83 in func1) | 2018-01-09 14:39:32 INFO (receiver.go:318) - no data received
2018-01-09 14:39:32 UTC | ERROR | (apm.go:95 in func2) | seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check file_handle
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check cpu
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check file_handle, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check io
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check cpu, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check load
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check load, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check memory
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check io, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check memory, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check uptime
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check uptime, next runs will be logged every 20 runs
2018-01-09 14:39:42 UTC | INFO | (runner.go:242 in work) | Running check ntp
2018-01-09 14:39:42 UTC | INFO | (runner.go:298 in work) | Done running check ntp, next runs will be logged every 20 runs
2018-01-09 14:40:27 UTC | INFO | (transaction.go:131 in Process) | successfully posted payload to 'https://6-0-0-app.agent.datadoghq.com/api/v1/series?api_key=*************************'%!(EXTRA string={"status": "ok"})
2018-01-09 14:40:32 UTC | INFO | (apm.go:83 in func1) | 2018-01-09 14:40:32 INFO (receiver.go:318) - no data received
2018-01-09 14:40:32 UTC | ERROR | (apm.go:95 in func2) | seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-01-09 14:41:32 UTC | ERROR | (apm.go:95 in func2) | seelog internal error: mkdir /var/log/datadog/: read-only file system
2018-01-09 14:41:32 UTC | INFO | (apm.go:83 in func1) | 2018-01-09 14:41:32 INFO (receiver.go:318) - no data received
```

Is there a way to disable or redirect these? It makes Rails console tedious/unusable.

Our current config vars look like:

```
DD_API_KEY=[API_KEY]
DD_APM_ENABLED=true
DD_HOSTNAME='[HOSTNAME]'
DD_SERVICE_ENV=staging
DD_SERVICE_NAME=web
```

Switching to the `#legacy` buildpack fixed this for us.

**Comment by kikitux** [comment]
Perhaps this can be made configurable:
https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L60

```
  # Run the Datadog Agent
  echo "Starting Datadog Agent on dyno $DYNO"
  bash -c "PYTHONPATH=$DD_DIR/embedded/lib/python2.7 $DD_BIN_DIR/agent -c $DATADOG_CONF start 2>&1 &"
```

give the option to manage stdout and stderr

**Comment by jyee** [comment]
@kikitux You can disable the logging to console by setting the env var `DD_LOG_TO_CONSOLE=false`.

One thing to note however is that it will not completely disable the console logging due to the way that certain components in Agent 6 operate. But, it should cut down on a lot of the info messages.

**Comment by the-mace** [comment]
The inability to STOP DD from spewing things to output regardless of loglevels etc is a real pain. There needs to be a control to stop all output from the agent. All the echos in `https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L60` are not good.

**Comment by arapulido** [comment]
> The inability to STOP DD from spewing things to output regardless of loglevels etc is a real pain. There needs to be a control to stop all output from the agent. All the echos in `https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L60` are not good.

Hello @the-mace . We are trying to make this better, so we want to investigate different scenarios. Have you tried setting DD_LOG_TO_CONSOLE to true in your Heroku app env variables? Does that help in anyway? What version of the agent are you running? Thanks!

**Comment by the-mace** [comment]
I'm not sure if you've looked at the code that's causing the issue:
https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L60
There are no checks for flags like DD_LOG_TO_CONSOLE etc in there. It echo's to the console regardless of any setting.
I'd recommend something along these lines:
https://github.com/ApplauseAQI/heroku-buildpack-datadog/commit/bb2aee00ba15314b3923ae175ed251cee4317fd4
Depending what levels of logging would make sense.

**Comment by arapulido** [comment]
Ah, OK, you are complaining about the echo's of the datadog.sh script, rather than the agent itself. There are several issues here. I think the original issue was complaining about the agent itself.

**Comment by the-mace** [comment]
Yes, sorry its the script which is chatty which means you get unwanted output in things like:
`heroku run python manage.py dumpdata --indent 2 signup --remote production >data.json`

**Comment by arapulido** [comment]
This is now fixed in release `1.16`: https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/1.16 if you use the agent pinned version (`6.18`, `7.18`) or newer

**Comment by bradical** [comment]
I'm not 100% sure this is the same thing but I'm still seeing all of this in the console when I connect via `heroku console` when using buildpack: `https://github.com/DataDog/heroku-buildpack-datadog.git#1.24`

Is there any way to suppress this stuff?

```
2021-03-10 00:45:37 UTC | PROCESS | INFO | (collector.go:158 in runCheck) | Finished process check #5 in 3.370566ms. First 5 check runs finished, next runs will be logged every 20 runs.
2021-03-10 00:45:37 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:disk | Running check
2021-03-10 00:45:37 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:disk | Done running check
2021-03-10 00:45:42 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:network | Running check
2021-03-10 00:45:42 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:network | Done running check
2021-03-10 00:45:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:load | Running check
2021-03-10 00:45:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:load | Done running check
2021-03-10 00:45:44 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:file_handle | Running check
2021-03-10 00:45:44 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:file_handle | Done running check
2021-03-10 00:45:45 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:cpu | Running check
2021-03-10 00:45:45 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:cpu | Done running check
2021-03-10 00:45:49 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:uptime | Running check
2021-03-10 00:45:49 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:uptime | Done running check
2021-03-10 00:45:50 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:memory | Running check
2021-03-10 00:45:50 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:memory | Done running check
2021-03-10 00:45:51 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:io | Running check
2021-03-10 00:45:51 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:io | Done running check
2021-03-10 00:45:52 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:disk | Running check
2021-03-10 00:45:52 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:disk | Done running check
2021-03-10 00:45:57 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:network | Running check
2021-03-10 00:45:57 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:network | Done running check
2021-03-10 00:45:58 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:load | Running check
2021-03-10 00:45:58 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:load | Done running check
2021-03-10 00:45:59 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:file_handle | Running check
2021-03-10 00:45:59 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:file_handle | Done running check
2021-03-10 00:46:00 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:cpu | Running check
2021-03-10 00:46:00 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:cpu | Done running check
2021-03-10 00:46:04 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:uptime | Running check
2021-03-10 00:46:04 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:uptime | Done running check
2021-03-10 00:46:05 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:memory | Running check
2021-03-10 00:46:05 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:memory | Done running check
2021-03-10 00:46:06 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:io | Running check
2021-03-10 00:46:06 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:io | Done running check
2021-03-10 00:46:07 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:disk | Running check
2021-03-10 00:46:07 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:disk | Done running check
2021-03-10 00:46:12 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:network | Running check
2021-03-10 00:46:12 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:network | Done running check
2021-03-10 00:46:13 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:load | Running check
2021-03-10 00:46:13 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:load | Done running check
2021-03-10 00:46:14 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:file_handle | Running check
2021-03-10 00:46:14 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:file_handle | Done running check
2021-03-10 00:46:15 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:cpu | Running check
2021-03-10 00:46:15 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:cpu | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:19 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:uptime | Running check
2021-03-10 00:46:19 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:uptime | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:20 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:memory | Running check
2021-03-10 00:46:20 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:memory | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:io | Running check
2021-03-10 00:46:21 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:io | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:22 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:disk | Running check
2021-03-10 00:46:22 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:disk | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:network | Running check
2021-03-10 00:46:27 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:network | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:28 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:load | Running check
2021-03-10 00:46:28 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:load | Done running check, next runs will be logged every 500 runs
2021-03-10 00:46:29 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | check:file_handle | Running check
2021-03-10 00:46:29 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | check:file_handle | Done running check, next runs will be logged every 500 runs
```

**Comment by arapulido** [comment]
@bradical This might help: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#limiting-datadogs-console-output

It  would be `DD_LOG_LEVEL=off` or `DD_LOG_LEVEL=critical`

**Comment by bradical** [comment]
I have tried changing the `DD_LOG_LEVEL` property to `CRITICAL` but I'm still seeing INFO logging when connecting. I'm reviewing your documentation and am trying to understand if this kind of property change requires a slug recompilation or not: https://github.com/DataDog/heroku-buildpack-datadog#upgrading-and-slug-recompilation

**Comment by arapulido** [comment]
@bradical No, it is not needed.

How are you setting up that variable? I just tried in one of my applications, and setting `DD_LOG_LEVEL` to `CRITICAL` removes the chatty logs.

What version of the buildpack and the datadog agent are you running?

**Comment by bradical** [comment]
> How are you setting up that variable? I just tried in one of my applications, and setting `DD_LOG_LEVEL` to `CRITICAL` removes the chatty logs.

Setting it in Heroku as a Config Var

> What version of the buildpack...

https://github.com/DataDog/heroku-buildpack-datadog.git#1.24

> ... and the datadog agent are you running?

No idea. I'm not specifying one in my config. Does it default to something?

<img width="755" alt="image" src="https://user-images.githubusercontent.com/191132/110820217-e7a6c300-825c-11eb-822b-01af2578673b.png">

**Comment by arapulido** [comment]
mmm, that should be good enough. Can you run the following command in your console, please?

`agent-wrapper status`, please? You only need to paste the output that looks like:
```

===============
Agent (v7.26.0)
===============

  Status date: 2021-03-11 16:31:39.894546 UTC
  Agent start: 2021-03-11 16:31:31.020040 UTC
  Pid: 96
  Go Version: go1.14.12
  Python Version: 3.8.5
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log File: /app/.apt/var/log/datadog/datadog.log
  Log Level: CRITICAL

```

**Comment by bradical** [comment]
Like this?

```
> agent-wrapper status
SyntaxError: (irb):17: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
agent-wrapper status
                    ^
```

**Comment by arapulido** [comment]
But in bash, not the ruby console, so the command can work correctly

**Comment by bradical** [comment]
How do I get to `bash` from `heroku console`?

**Comment by arapulido** [comment]
Instead of `heroku console` you can do `heroku ps:exec` that will ssh into
your application dyno

**Comment by bradical** [comment]
Hmm, this is odd, that is telling me that the API key is not set but it's in my Config Vars

```
$ heroku ps:exec
Establishing credentials... done
Connecting to web.1 on ⬢ clive-io... 
DD_API_KEY environment variable not set. Run: heroku config:add DD_API_KEY=<your API key>
The Datadog Agent has been disabled. Unset the DISABLE_DATADOG_AGENT or set missing environment variables.
~ $ agent-wrapper status
Getting the status from the agent.

===============
Agent (v6.26.0)
===============

  Status date: 2021-03-11 17:04:48.319015 UTC
  Agent start: 2021-03-11 14:29:58.418799 UTC
  Pid: 54
  Go Version: go1.14.12
  Python Version: 2.7.18
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log File: /app/.apt/var/log/datadog/datadog.log
  Log Level: CRITICAL

  Paths
  =====
    Config File: /app/.apt/etc/datadog-agent/datadog.yaml
    conf.d: /app/.apt/etc/datadog-agent/conf.d
    checks.d: /app/.apt/etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 275µs
    System UTC time: 2021-03-11 17:04:48.319015 UTC

  Host Info
  =========
    bootTime: 2021-02-11 15:23:36.000000 UTC
    kernelArch: x86_64
    kernelVersion: 4.4.0-1085-aws
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 16.04
    procs: 11
    uptime: 671h6m26s
    virtualizationRole: guest
    virtualizationSystem: lxc

  Hostnames
  =========
    hostname: clive-io
    socket-fqdn: fcc0d126-fabe-405b-93cf-3b3866f7a44a.prvt.dyno.rt.heroku.com.
    socket-hostname: fcc0d126-fabe-405b-93cf-3b3866f7a44a
    host tags:
      dyno:web.1
      dynotype:web
      buildpackversion:1.24
      appname:clive-io
    hostname provider: configuration

  Metadata
  ========
    hostname_source: configuration

=========
Collector
=========

  Running Checks
  ==============
   

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
      Total Runs: 620
      Metric Samples: Last Run: 8, Total: 4,954
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2021-03-11 17:04:47.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:47.000000 UTC
      
    
    disk (4.1.1)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/disk.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 220, Total: 136,180
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 126ms
      Last Execution Date : 2021-03-11 17:04:39.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:39.000000 UTC
      
    
    file_handle
    -----------
      Instance ID: file_handle [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 5, Total: 3,095
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2021-03-11 17:04:46.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:46.000000 UTC
      
    
    io
    --
      Instance ID: io [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/io.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 273, Total: 168,798
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Last Execution Date : 2021-03-11 17:04:38.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:38.000000 UTC
      
    
    load
    ----
      Instance ID: load [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/load.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 6, Total: 3,714
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2021-03-11 17:04:45.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:45.000000 UTC
      
    
    memory
    ------
      Instance ID: memory [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/memory.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 18, Total: 11,142
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2021-03-11 17:04:37.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:37.000000 UTC
      
    
    network (2.1.1)
    ---------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/network.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 31, Total: 19,189
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 5ms
      Last Execution Date : 2021-03-11 17:04:44.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:44.000000 UTC
      
    
    ntp
    ---
      Instance ID: ntp:d884b5186b651429 [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
      Total Runs: 11
      Metric Samples: Last Run: 1, Total: 11
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 11
      Average Execution Time : 2.005s
      Last Execution Date : 2021-03-11 17:00:02.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:00:02.000000 UTC
      
    
    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 619
      Metric Samples: Last Run: 1, Total: 619
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2021-03-11 17:04:36.000000 UTC
      Last Successful Execution Date : 2021-03-11 17:04:36.000000 UTC
      
========
JMXFetch
========

  Information
  ==================
  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  Transactions
  ============
    Deployments: 0
    Dropped: 0
    DroppedOnInput: 0
    Nodes: 0
    Pods: 0
    ReplicaSets: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Services: 0

  Transaction Successes
  =====================
    Total number: 1305
    Successes By Endpoint:
      check_run_v1: 619
      intake: 67
      series_v1: 619

  API Keys status
  ===============
    API key ending with 1fd9d: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 1fd9d

==========
Logs Agent
==========


  Logs Agent is not running

=========
APM Agent
=========
  Status: Running
  Pid: 56
  Uptime: 9289 seconds
  Mem alloc: 18,584,104 bytes
  Hostname: clive-io
  Receiver: localhost:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    From ruby 2.4.3 (ruby-x86_64-linux), client 0.37.0
      Traces received: 3 (11,424 bytes)
      Spans received: 26
      
    Default priority sampling rate: 100.0%
    Priority sampling rate for 'service:clive_api,env:production': 100.0%

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes

=========
Aggregator
=========
  Checks Metric Sample: 357,630
  Dogstatsd Metric Sample: 92,510
  Event: 1
  Events Flushed: 1
  Number Of Flushes: 619
  Series Flushed: 347,627
  Service Check: 4,975
  Service Checks Flushed: 5,590

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 92,509
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 8,336,291
  Udp Packet Reading Errors: 0
  Udp Packets: 60,786
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
  Unterminated Metric Errors: 0
```

**Comment by arapulido** [comment]
Do not worry about the DD_API_KEY error, this is only happening in the
ps:exec environment.

I am a bit lost. Everything should be ready and you shouldn't see the logs.

Do you get log output when you do: `heroku run bash` ?

**Comment by bradical** [comment]
Hmm, upon connecting to console with `heroku console` now, I'm no longer seeing the additional logging. Perhaps the log level config change had not taken effect yet?

Not seeing any in `heroku run bash` either.

I noticed my agent version is behind yours. Is mine pinned in some way here? As I said, I'm not manually specifying a version anywhere to my knowledge.

**Comment by arapulido** [comment]
@bradical Yes, it seems that the log level config change hadn't taken effect. You are good to go :)

As for the version, agent versions 7.xx and 6.xx are equivalent, but one is using Python3 and the other Python2. We recommend using version 7.xx whenever possible. To get that version, please, set the following env variable:

`DD_AGENT_MAJOR_VERSION=7`
